config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :auctions
    resources :bids
    resource :auction_settings, only: ['show', 'update', 'edit']
  end
  resources :auctions, only: %i{index show}
  resources :votes, only: %i{index}
  get 'vote_up', to: "auctions#vote_up"
  get 'vote_down', to: "auctions#vote_down"
  get 'vote_count', to: "auctions#vote_count"
  get 'starting_soon', to: "auctions#starting_soon"
  get 'ending_soon', to: "auctions#ending_soon"
  get 'recently_completed', to: "auctions#recently_completed"

  resources :bids, only: %i{index new create}
end

app/models/spree/auction_ability.rb
class Spree::AuctionAbility
  include CanCan::Ability

  def initialize(user)
    can :create, Spree::Auction do
      user.admin?
    end

    can %i{edit update destroy delete clone}, Spree::Auction do |auction|
      auction.creator_id == user.id
    end
  end
end

app/models/spree/bid.rb
class Spree::Bid < Spree::Base
  belongs_to :auction, class_name: 'Spree::Auction'
  belongs_to :bidder, class_name: 'Spree::User'

  validates :auction_id, presence: true
  validates :bidder_id, presence: true
  validates :amount, presence: true

  extend Spree::DisplayMoney
  money_methods :amount

  scope :accepted, -> { where(accepted: true) }
  scope :visible, -> { where(visible: true) }
  scope :delinquent, -> { where(delinquent: true) }
  scope :not_delinquent, -> { where(delinquent: false) }

  def is_autobid?
    !visible && accepted
  end

  def bidder_display_name
    bidder.email
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :auctions, class_name: 'Spree::Auction'
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  has_many :bids, class_name: 'Spree::Bid', foreign_key: "bidder_id"
  has_many :auctions, class_name: 'Spree::Auction', through: :bids
  acts_as_voter
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  has_one :auction, class_name: 'Spree::Auction'
end

app/controllers/spree/admin/auction_settings_controller.rb
class Spree::Admin::AuctionSettingsController < Spree::Admin::BaseController
  def edit
    @config = Spree::AuctionSettings::Config
  end

  def update
    config = Spree::AuctionSettings::Config

    params.each do |name, value|
      next unless config.has_preference? name
      config[name] = value
    end

    redirect_to edit_admin_auction_settings_path
  end
end

app/controllers/spree/admin/auctions_controller.rb
class Spree::Admin::AuctionsController < Spree::Admin::ResourceController
  create.before :create_before
  helper_method :disable_on_start
  helper_method :disable_on_complete
  helper Spree::Helpers::LocalTimeHelper

  def index
    session[:return_to] = request.url
    @collection = @collection.current_end_datetime_descending
    respond_with(@collection)
  end

  def show
    redirect_to action: :edit
  end

  private

  def disable_on_start(auction_started, enabled_options)
    if auction_started
      { readonly: true, disabled: true }.merge(enabled_options)
    else
      enabled_options
    end
  end

  def disable_on_complete(auction_complete, enabled_options)
    if auction_complete
      { readonly: true, disabled: true }.merge(enabled_options)
    else
      enabled_options
    end
  end

  def create_before
    @auction.creator = spree_current_user if spree_user_signed_in?
  end

  def permitted_auction_attributes
    %i{id title description starting_datetime planned_end_datetime starting_price reserve_price bid_increment time_increment countdown product_id checkout_time_minutes}
  end

  def permitted_resource_params
    params.require(:auction).permit(permitted_auction_attributes)
  end
end

app/controllers/spree/admin/bids_controller.rb
class Spree::Admin::BidsController < Spree::Admin::ResourceController
end

app/controllers/spree/admin/resource_controller_decorator.rb
Spree::Admin::ResourceController.class_eval do
  around_action :set_time_zone, if: :spree_current_user

  private

  def set_time_zone(&block)
    Time.use_zone(spree_current_user.time_zone, &block)
  end
end

app/controllers/spree/auctions_controller.rb
class Spree::AuctionsController < Spree::StoreController
  helper Spree::BaseHelper
  helper Spree::Helpers::LocalTimeHelper
  helper_method :config

  def index
    @auctions = Spree::Auction.in_progress.incomplete.current_end_datetime_ascending
  end

  def starting_soon
    @auctions = Spree::Auction.incomplete.starting_soon.starting_datetime_ascending
    render :index
  end

  def ending_soon
    @auctions = Spree::Auction.incomplete.ending_soon
    render :index
  end

  def recently_completed
    @auctions = Spree::Auction.recently_completed
    render :index
  end

  def show
    @auction = Spree::Auction.find(params[:id])
    @product = @auction.product
    @product_properties = @product.product_properties.includes(:property)
  end

  def vote_count
    auction = Spree::Auction.find_by(id: params[:auction_id])
    votes = auction.cached_votes_up
    render json: { votes: votes }
  end

  def vote_up
    auction = Spree::Auction.find_by(id: params[:auction_id])
    user = Spree::User.find_by(id: params[:user_id])
    auction.liked_by user
    votes = auction.cached_votes_up
    render json: { votes: votes, voted_for: 1 }
  end

  def vote_down
    auction = Spree::Auction.find_by(id: params[:auction_id])
    user = Spree::User.find_by(id: params[:user_id])
    auction.downvote_from user
    votes = auction.cached_votes_up
    render json: { votes: votes, voted_for: 0 }
  end
end

app/controllers/spree/bids_controller.rb
class Spree::BidsController < Spree::StoreController
  def index
    @auction = Spree::Auction.find(params[:auction_id])
    @bids = @auction.visible_bids_in_chron_order
  end

  def new
    @auction = Spree::Auction.find(params[:auction_id])
    if spree_current_user
      @bid = Spree::Bid.new(auction: @auction)
    else
      flash[:error] = Spree.t("must_be_signed_in_to_bid")
      redirect_to auction_path @auction
    end
  end

  def create
    @auction = Spree::Auction.find(params[:auction_id])
    if spree_current_user
      @bid = Spree::Bid.create(auction: @auction, bidder: spree_current_user, amount: params[:amount])
      @recorded_bid, message = @auction.receive_bid(@bid)
      if @recorded_bid
        flash[:success] = message
      else
        flash[:error] = message
      end
    else
      flash[:error] = Spree.t("must_be_signed_in_to_bid")
    end
    redirect_to auction_path @auction
  end

  private

  def flash_message_for(object, event_sym)
    resource_desc  = object.class.model_name.human
    resource_desc += " \"#{object.name}\"" if object.respond_to?(:name) && object.name.present?
    t(event_sym, resource: resource_desc, scope: 'spree')
  end

  def permitted_bid_attributes
    %i{auction_id amount}
  end

  def bid_params
    params.require(:bid).permit(permitted_bid_attributes)
  end
end

app/controllers/spree/helpers/local_time_helper.rb
module Spree::Helpers::LocalTimeHelper
  module LocalTime
    mattr_accessor(:default_time_format) { "%A, %B %e %Y %l:%M%p" }
    mattr_accessor(:default_date_format) { "%B %e, %Y" }

    class Engine < ::Rails::Engine
    end
  end
  def local_time(time, options = nil)
    time = utc_time(time)

    options, format = extract_options_and_value(options, :format)
    format = find_time_format(format)

    options[:data] ||= {}
    options[:data].merge! local: :time, format: format

    time_tag time, time.strftime(format), options
  end

  def local_date(time, options = nil)
    options, format = extract_options_and_value(options, :format)
    options[:format] = format || LocalTime.default_date_format
    local_time time, options
  end

  def local_relative_time(time, options = nil)
    time = utc_time(time)
    options, type = extract_options_and_value(options, :type)

    options[:data] ||= {}
    options[:data].merge! local: type

    time_tag time, time.strftime(LocalTime.default_time_format), options
  end

  def local_time_ago(time, options = nil)
    options, * = extract_options_and_value(options, :type)
    options[:type] = 'time-ago'
    local_relative_time time, options
  end

  def utc_time(time_or_date)
    if time_or_date.respond_to?(:in_time_zone)
      time_or_date.in_time_zone.utc
    else
      time_or_date.to_time.utc
    end
  end

  private
    def find_time_format(format)
      if format.is_a?(Symbol)
        if (i18n_format = I18n.t("time.formats.#{format}", default: [:"date.formats.#{format}", ''])).present?
          i18n_format
        elsif (date_format = Time::DATE_FORMATS[format] || Date::DATE_FORMATS[format])
          date_format.is_a?(Proc) ? LocalTime.default_time_format : date_format
        else
          LocalTime.default_time_format
        end
      else
        format.presence || LocalTime.default_time_format
      end
    end

    def extract_options_and_value(options, value_key = nil)
      case options
      when Hash
        value = options.delete(value_key)
        [ options, value ]
      when NilClass
        [ {} ]
      else
        [ {}, options ]
      end
    end
end

app/controllers/spree/users_controller_decorator.rb
if !Rails.env.test?
  Spree::UsersController.class_eval do
    helper Spree::Helpers::LocalTimeHelper
  end
end

app/controllers/spree/votes_controller.rb
class Spree::VotesController < Spree::StoreController
  def index
    @auctions = spree_current_user.find_up_voted_items
  end
end

app/helpers/spree/strong_params_decorator.rb
Spree::Core::ControllerHelpers::StrongParameters.class_eval do
  def permitted_user_attributes
    permitted_attributes.user_attributes + [
      bill_address_attributes: permitted_address_attributes,
      ship_address_attributes: permitted_address_attributes
    ] + %i{time_zone username}
  end
end

app/views/spree/auctions/_bid_form.html.erb
<% min_bid = @auction.current_price + @auction.bid_increment %>

<%= form_for :bid, url: bids_path do |f| %>
  <div id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
    <div data-hook="product_price" class="columns five alpha">

      <div id="product-price">
        <% if @auction.complete %>
          <h6 class="product-section-title"><%= t('spree.winning_bid') %></h6>
        <% else %>
          <h6 class="product-section-title"><%= t('spree.current_price') %></h6>
        <% end %>
        <div>
          <span class="price selling" itemprop="price" content="<%= @auction.current_price.to_d %>">
            <%= @auction.display_current_price %>
          </span>
        </div>
        <% if @auction.reserve_price > 0 %>
          <div>
            <% if @auction.reserve_met? %>
              <span class="green">
                <i class="fa fa-check-circle" aria-hidden="true"></i>
                <%= t("spree.reserve_met") %>
              </span>
            <% else %>
              <span class="red">
                <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
                <%= t("spree.reserve_not_met") %>
              </span>
            <% end %>
          </div>
        <% end %>
        <div>
          <span class="bold">
            <%= bid_count = @auction.visible_bids.count %>
            <% if bid_count == 1 %>
              <%= Spree.t("spree.bid") %>
            <% else %>
              <%= Spree.t("spree.bids") %>
            <% end %>
          </span>
        </div>
        <%= render partial: 'spree/shared/votes', locals: { auction: @auction } %>
        <% if !@auction.complete %>
          <div>
            <span>
              <%= t("spree.min_bid") %>:
            </span>
            <span>
              <%= number_to_currency(min_bid, :unit => "$") %>
            </span>
          </div>
        <% end %>
      </div>
      <% if spree_current_user %>
        <% is_highest_bidder = @auction.highest_bidder_id == spree_current_user.id %>
      <% else %>
        <% is_highest_bidder = false %>
      <% end %>
      <% if @auction.complete %>
        <% if is_highest_bidder  %>
          <h6 class="product-section-title green">
            <%= Spree.t("you_have_won_this_auction") %>
          </h6>
          <%= render partial: 'spree/shared/checkout_in', locals: { auction: @auction } %>
          <h6 class="product-section-title">
            <%= Spree.t("view_order_or_checkout") %>:
          </h6>
          <%= render partial: 'spree/shared/auction_order_link', locals: { auction: @auction } %>
        <% end %>
      <% else %>
        <%= hidden_field_tag :auction_id, @auction.id %>
        <div class="add-to-cart">
          <%= number_field_tag :amount, min_bid, class: 'title', min: min_bid, step: 0.01, disabled: !@auction.in_progress? %>
          <%= button_tag class: 'large primary', id: 'add-to-cart-button', disabled: !@auction.in_progress?, data: { confirm: Spree.t("bid_confirmation_message") },  type: :submit do %>
            <%= t('spree.bid') %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= render partial: 'bids' %>
  </div>
<% end %>

app/views/spree/auctions/_bids.html.erb
<% @bids = @auction.visible_bids_in_chron_order.limit(Spree::AuctionSettings::Config.number_of_bids_to_show) %>
<% if @bids.any? %>
  <div id="bids" class="columns five alpha" data-hook="bids">
    <table data-hook="visible-bids-table">
      <thead>
        <tr>
          <th>
            <%= Spree.t("bidder") %>
          </th>
          <th>
            <%= Spree.t("amount") %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @bids.each_with_index do |bid, i| %>
          <% if i == 0 %>
            <tr class="odd">
              <td>
                <%= bid.bidder_display_name %>
              </td>
              <% if spree_current_user && @auction.highest_bidder_id == spree_current_user.id %>
                <td>
                  <%= bid.display_amount %>
                  <span class="green">
                    <% highest_bid = @auction.highest_bid %>
                    <% if highest_bid.is_autobid? %>
                      (<%= highest_bid.display_amount %>)
                    <% end %>
                  </span>
                </td>
              <% else %>
                <td>
                  <%= bid.display_amount %>
                </td>
              <% end %>
            </tr>
          <% else %>
            <tr>
              <td>
                <%= bid.bidder_display_name %>
              </td>
              <td>
                <%= bid.display_amount %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/auctions/_image.html.erb
<% if defined?(image) && image %>
  <%= render 'spree/shared/image', image: image, size: :product, itemprop: "image" %>
<% else %>
  <%= render 'spree/shared/image', image: @product.display_image, size: :product, itemprop: "image" %>
<% end %>

app/views/spree/auctions/_promotions.html.erb
<% promotions = @product.possible_promotions %>
<% if promotions.any? %>
  <div id="promotions">
    <h3><%= t('spree.promotions') %></h3>
    <% promotions.each do |promotion| %>
    <div>
      <h4><%= promotion.name %></h4>
      <p><%= promotion.description %></p>
      <% if promotion.products.any? %>
      <ul>
        <% promotion.products.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/spree/auctions/_properties.html.erb
<% unless @product_properties.empty? %>  
  <h6 class="product-section-title"><%= t('spree.properties')%></h6>
  <table id="product-properties" class="table-display" data-hook>
    <tbody>
      <% @product_properties.each do |product_property| %>
        <% css_class = cycle('even', 'odd', name: "properties") %>
        <tr class="<%= css_class %>">
          <td><strong><%= product_property.property.presentation %></strong></td>
          <td><%= product_property.value %></td>
        </tr>
      <% end %>
      <% reset_cycle('properties') %>
    </tbody>
  </table>
<% end %>

app/views/spree/auctions/_taxons.html.erb
<% if !@product.taxons.blank? %>
  <div id="taxon-crumbs" data-hook class="alpha columns five omega">
    <h6 class="product-section-title"><%= t('spree.look_for_similar_items') %></h6>

    <div data-hook="product_taxons">
      <ul id="similar_items_by_taxon" data-hook>
      <% @product.taxons.each do |taxon| %>
        <li><%= link_to taxon.name, seo_url(taxon) %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

app/views/spree/auctions/_thumbnails.html.erb
<%# no need for thumbnails unless there is more than one image %>
<% if (@product.images + @product.variant_images).uniq.size > 1 %>
  <ul id="product-thumbnails" class="thumbnails inline" data-hook>
    <% @product.images.each do |i| %>
      <li class='tmb-all tmb-<%= i.viewable.id %>'>
        <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
      </li>
    <% end %>

    <% if @product.has_variants? %>
      <% @product.variant_images.each do |i| %>
        <% next if @product.images.include?(i) %>
        <li class='vtmb tmb-<%= i.viewable.id %>'>
          <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/spree/auctions/index.html.erb
<div data-hook="homepage_auctions">
  <%= render partial: 'spree/shared/auctions', locals: { auctions: @auctions } %>
</div>

app/views/spree/auctions/show.html.erb
<h1>
  <%= @auction.title  %>
</h1>
<div>
  <%= render partial: 'spree/shared/time_in_words_display', locals: { auction: @auction } %>
</div>
<div>
  <%= Spree.t("ends_at") %>
  <span class="bold">
    <%= local_time(@auction.current_end_datetime, "%l:%M%p on %A, %B %e") %>
  </span>
</div>
<p>
  <%= @auction.description  %>
</p>
<div data-hook="product_show" itemscope itemtype="http://schema.org/Product">
  <% @body_id = 'product-details' %>

  <div class="columns six alpha" data-hook="product_left_part">
    <div class="row" data-hook="product_left_part_wrap">

      <div id="product-images" data-hook="product_images">
        <div id="main-image" data-hook>
          <%= render partial: 'image' %>
        </div>
        <div id="thumbnails" data-hook>
          <%= render partial: 'thumbnails' %>
        </div>
      </div>

      <div data-hook="product_properties">
        <%= render partial: 'properties' %>
      </div>

      <div data-hook="promotions">
        <%= render partial: 'promotions' %>
      </div>

    </div>
  </div>

  <div class="columns ten omega" data-hook="product_right_part">
    <div class="row" data-hook="product_right_part_wrap">

      <div id="product-description" data-hook="product_description">

        <h1 class="product-title" itemprop="name"><%= @product.name %></h1>

        <div itemprop="description" data-hook="description">
          <%= product_description(@product) rescue t('spree.product_has_no_description') %>
        </div>

        <div id="bid-form" data-hook="bid_form">
          <%= render partial: 'bid_form' %>
        </div>
      </div>
    </div>
  </div>