config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :auctions
    resources :bids
    resource :auction_settings, only: ['show', 'update', 'edit']
  end
  resources :auctions, only: %i{index show}
  resources :votes, only: %i{index}
  get 'vote_up', to: "auctions#vote_up"
  get 'vote_down', to: "auctions#vote_down"
  get 'vote_count', to: "auctions#vote_count"
  get 'starting_soon', to: "auctions#starting_soon"
  get 'ending_soon', to: "auctions#ending_soon"
  get 'recently_completed', to: "auctions#recently_completed"

  resources :bids, only: %i{index new create}
end

app/views/spree/admin/shared/_auction_links_to_order_info.html.erb
<%
  auctions = []
@order.variants.each do |variant|
  if auction = variant.auction
    auctions << auction
  end
end
%>
<% if !auctions.empty? %>
  <dt data-hook='admin_order_tab_auctions_title'><%= Spree.t(:auctions) %>:</dt>
  <dd id='auction_links'>
    <% auctions.each do |auction| %>
      <p>
        <%= link_to auction.title, admin_auction_path(auction) %>
      </p>
    <% end %>
  </dd>
<% end %>

app/views/spree/admin/shared/_auction_settings_button.html.erb
<li>
  <%= link_to Spree.t(:auction), edit_admin_auction_settings_path  %>
</li>

app/views/spree/admin/shared/_auctions_tab.html.erb
<% if can? :create, Spree::Auction %>
  <%= tab :auctions, icon: 'gavel' %>
<% end %>

app/views/spree/admin/shared/_time_zone_field.html.erb
<%= f.field_container :time_zone do %>
  <%= f.label :time_zone %>
  <%= f.time_zone_select :time_zone, nil, {}, { class: "custom-select", default: "Pacific Time (US & Canada)" } %>
  <%= f.error_message_on :time_zone %>
<% end %>