config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :auctions
    resources :bids
    resource :auction_settings, only: ['show', 'update', 'edit']
  end
  resources :auctions, only: %i{index show}
  resources :votes, only: %i{index}
  get 'vote_up', to: "auctions#vote_up"
  get 'vote_down', to: "auctions#vote_down"
  get 'vote_count', to: "auctions#vote_count"
  get 'starting_soon', to: "auctions#starting_soon"
  get 'ending_soon', to: "auctions#ending_soon"
  get 'recently_completed', to: "auctions#recently_completed"

  resources :bids, only: %i{index new create}
end

app/models/spree/auction_ability.rb
class Spree::AuctionAbility
  include CanCan::Ability

  def initialize(user)
    can :create, Spree::Auction do
      user.admin?
    end

    can %i{edit update destroy delete clone}, Spree::Auction do |auction|
      auction.creator_id == user.id
    end
  end
end

app/models/spree/bid.rb
class Spree::Bid < Spree::Base
  belongs_to :auction, class_name: 'Spree::Auction'
  belongs_to :bidder, class_name: 'Spree::User'

  validates :auction_id, presence: true
  validates :bidder_id, presence: true
  validates :amount, presence: true

  extend Spree::DisplayMoney
  money_methods :amount

  scope :accepted, -> { where(accepted: true) }
  scope :visible, -> { where(visible: true) }
  scope :delinquent, -> { where(delinquent: true) }
  scope :not_delinquent, -> { where(delinquent: false) }

  def is_autobid?
    !visible && accepted
  end

  def bidder_display_name
    bidder.email
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :auctions, class_name: 'Spree::Auction'
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  has_many :bids, class_name: 'Spree::Bid', foreign_key: "bidder_id"
  has_many :auctions, class_name: 'Spree::Auction', through: :bids
  acts_as_voter
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  has_one :auction, class_name: 'Spree::Auction'
end

app/controllers/spree/admin/auction_settings_controller.rb
class Spree::Admin::AuctionSettingsController < Spree::Admin::BaseController
  def edit
    @config = Spree::AuctionSettings::Config
  end

  def update
    config = Spree::AuctionSettings::Config

    params.each do |name, value|
      next unless config.has_preference? name
      config[name] = value
    end

    redirect_to edit_admin_auction_settings_path
  end
end

app/controllers/spree/admin/auctions_controller.rb
class Spree::Admin::AuctionsController < Spree::Admin::ResourceController
  create.before :create_before
  helper_method :disable_on_start
  helper_method :disable_on_complete
  helper Spree::Helpers::LocalTimeHelper

  def index
    session[:return_to] = request.url
    @collection = @collection.current_end_datetime_descending
    respond_with(@collection)
  end

  def show
    redirect_to action: :edit
  end

  private

  def disable_on_start(auction_started, enabled_options)
    if auction_started
      { readonly: true, disabled: true }.merge(enabled_options)
    else
      enabled_options
    end
  end

  def disable_on_complete(auction_complete, enabled_options)
    if auction_complete
      { readonly: true, disabled: true }.merge(enabled_options)
    else
      enabled_options
    end
  end

  def create_before
    @auction.creator = spree_current_user if spree_user_signed_in?
  end

  def permitted_auction_attributes
    %i{id title description starting_datetime planned_end_datetime starting_price reserve_price bid_increment time_increment countdown product_id checkout_time_minutes}
  end

  def permitted_resource_params
    params.require(:auction).permit(permitted_auction_attributes)
  end
end

app/controllers/spree/admin/bids_controller.rb
class Spree::Admin::BidsController < Spree::Admin::ResourceController
end

app/controllers/spree/admin/resource_controller_decorator.rb
Spree::Admin::ResourceController.class_eval do
  around_action :set_time_zone, if: :spree_current_user

  private

  def set_time_zone(&block)
    Time.use_zone(spree_current_user.time_zone, &block)
  end
end

app/controllers/spree/auctions_controller.rb
class Spree::AuctionsController < Spree::StoreController
  helper Spree::BaseHelper
  helper Spree::Helpers::LocalTimeHelper
  helper_method :config

  def index
    @auctions = Spree::Auction.in_progress.incomplete.current_end_datetime_ascending
  end

  def starting_soon
    @auctions = Spree::Auction.incomplete.starting_soon.starting_datetime_ascending
    render :index
  end

  def ending_soon
    @auctions = Spree::Auction.incomplete.ending_soon
    render :index
  end

  def recently_completed
    @auctions = Spree::Auction.recently_completed
    render :index
  end

  def show
    @auction = Spree::Auction.find(params[:id])
    @product = @auction.product
    @product_properties = @product.product_properties.includes(:property)
  end

  def vote_count
    auction = Spree::Auction.find_by(id: params[:auction_id])
    votes = auction.cached_votes_up
    render json: { votes: votes }
  end

  def vote_up
    auction = Spree::Auction.find_by(id: params[:auction_id])
    user = Spree::User.find_by(id: params[:user_id])
    auction.liked_by user
    votes = auction.cached_votes_up
    render json: { votes: votes, voted_for: 1 }
  end

  def vote_down
    auction = Spree::Auction.find_by(id: params[:auction_id])
    user = Spree::User.find_by(id: params[:user_id])
    auction.downvote_from user
    votes = auction.cached_votes_up
    render json: { votes: votes, voted_for: 0 }
  end
end

app/controllers/spree/bids_controller.rb
class Spree::BidsController < Spree::StoreController
  def index
    @auction = Spree::Auction.find(params[:auction_id])
    @bids = @auction.visible_bids_in_chron_order
  end

  def new
    @auction = Spree::Auction.find(params[:auction_id])
    if spree_current_user
      @bid = Spree::Bid.new(auction: @auction)
    else
      flash[:error] = Spree.t("must_be_signed_in_to_bid")
      redirect_to auction_path @auction
    end
  end

  def create
    @auction = Spree::Auction.find(params[:auction_id])
    if spree_current_user
      @bid = Spree::Bid.create(auction: @auction, bidder: spree_current_user, amount: params[:amount])
      @recorded_bid, message = @auction.receive_bid(@bid)
      if @recorded_bid
        flash[:success] = message
      else
        flash[:error] = message
      end
    else
      flash[:error] = Spree.t("must_be_signed_in_to_bid")
    end
    redirect_to auction_path @auction
  end

  private

  def flash_message_for(object, event_sym)
    resource_desc  = object.class.model_name.human
    resource_desc += " \"#{object.name}\"" if object.respond_to?(:name) && object.name.present?
    t(event_sym, resource: resource_desc, scope: 'spree')
  end

  def permitted_bid_attributes
    %i{auction_id amount}
  end

  def bid_params
    params.require(:bid).permit(permitted_bid_attributes)
  end
end

app/controllers/spree/helpers/local_time_helper.rb
module Spree::Helpers::LocalTimeHelper
  module LocalTime
    mattr_accessor(:default_time_format) { "%A, %B %e %Y %l:%M%p" }
    mattr_accessor(:default_date_format) { "%B %e, %Y" }

    class Engine < ::Rails::Engine
    end
  end
  def local_time(time, options = nil)
    time = utc_time(time)

    options, format = extract_options_and_value(options, :format)
    format = find_time_format(format)

    options[:data] ||= {}
    options[:data].merge! local: :time, format: format

    time_tag time, time.strftime(format), options
  end

  def local_date(time, options = nil)
    options, format = extract_options_and_value(options, :format)
    options[:format] = format || LocalTime.default_date_format
    local_time time, options
  end

  def local_relative_time(time, options = nil)
    time = utc_time(time)
    options, type = extract_options_and_value(options, :type)

    options[:data] ||= {}
    options[:data].merge! local: type

    time_tag time, time.strftime(LocalTime.default_time_format), options
  end

  def local_time_ago(time, options = nil)
    options, * = extract_options_and_value(options, :type)
    options[:type] = 'time-ago'
    local_relative_time time, options
  end

  def utc_time(time_or_date)
    if time_or_date.respond_to?(:in_time_zone)
      time_or_date.in_time_zone.utc
    else
      time_or_date.to_time.utc
    end
  end

  private
    def find_time_format(format)
      if format.is_a?(Symbol)
        if (i18n_format = I18n.t("time.formats.#{format}", default: [:"date.formats.#{format}", ''])).present?
          i18n_format
        elsif (date_format = Time::DATE_FORMATS[format] || Date::DATE_FORMATS[format])
          date_format.is_a?(Proc) ? LocalTime.default_time_format : date_format
        else
          LocalTime.default_time_format
        end
      else
        format.presence || LocalTime.default_time_format
      end
    end

    def extract_options_and_value(options, value_key = nil)
      case options
      when Hash
        value = options.delete(value_key)
        [ options, value ]
      when NilClass
        [ {} ]
      else
        [ {}, options ]
      end
    end
end

app/controllers/spree/users_controller_decorator.rb
if !Rails.env.test?
  Spree::UsersController.class_eval do
    helper Spree::Helpers::LocalTimeHelper
  end
end

app/controllers/spree/votes_controller.rb
class Spree::VotesController < Spree::StoreController
  def index
    @auctions = spree_current_user.find_up_voted_items
  end
end

app/helpers/spree/strong_params_decorator.rb
Spree::Core::ControllerHelpers::StrongParameters.class_eval do
  def permitted_user_attributes
    permitted_attributes.user_attributes + [
      bill_address_attributes: permitted_address_attributes,
      ship_address_attributes: permitted_address_attributes
    ] + %i{time_zone username}
  end
end

app/views/spree/shared/_auction_order_link.html.erb
<% highest_bidder = auction.highest_bidder_id == spree_current_user.id %>
<% if auction.complete && highest_bidder %>
  <% order = auction.order %>
  <% if order.complete? %>
    <%= link_to order.number, order %>
  <% else %>
    <%= link_to order.number, cart_path %>
  <% end %>
<% end %>

app/views/spree/shared/_auctions.html.erb
<% if auctions.any? %>
  <ul id="auctions" class="inline auction-listing" data-hook="auctions-index">
    <% auctions.each do |auction| %>
      <% product = auction.product %>
      <% url = spree.auction_path(auction) %>
      <li id="auction_<%= auction.id %>" class="columns three <%= cycle("alpha", "secondary", "", "omega secondary", name: "classes") %>" data-hook="auctions_list_item" itemscope>
        <div class="auction-image">
          <%= link_to(render('spree/shared/image', image: product.display_image, size: :small, itemprop: "image"), url, itemprop: 'url') %>
        </div>
        <%= link_to truncate(auction.title, length: 50), url, class: 'info', itemprop: "title", title: auction.title %>
        <div>
          <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
            <span class="price selling" itemprop="price" content="<%= auction.display_current_price %>">
              <%= auction.display_current_price %>
            </span>
          </span>
        </div>
        <%= render partial: 'spree/shared/time_in_words_display', locals: { auction: auction } %>
        <div>
          <span class="bold">
            <%= bid_count = auction.visible_bids.count %>
            <% if bid_count == 1 %>
              <%= Spree.t("spree.bid") %>
            <% else %>
              <%= Spree.t("spree.bids") %>
            <% end %>
          </span>
        </div>
        <%= render partial: 'spree/shared/votes', locals: { auction: auction } %>
          <% if auction.in_progress? %>
            <div>
              <%= link_to Spree.t("bid"), url, class: "button button-primary" %>
            </div>
          <% end %>
        </li>
      <% end %>
      <% reset_cycle("classes") %>
    </ul>
  <% end %>

app/views/spree/shared/_auctions_link.html.erb
<%= link_to Spree.t("current_auctions"), auctions_path %>
<%= link_to Spree.t("starting_soon"), starting_soon_path %>
<%= link_to Spree.t("ending_soon"), ending_soon_path %>
<%= link_to Spree.t("recently_completed"), recently_completed_path %>
<% if spree_current_user %>
  <%= link_to "#{Spree.t('watching')} (#{spree_current_user.find_up_voted_items.count})", votes_path %>
<% end %>

app/views/spree/shared/_auctions_table_show.html.erb
<% @auctions = spree_current_user.auctions.current_end_datetime_descending.uniq %>

<div data-hook="account_my_auctions" class="account-my-auctions">

  <h3><%= Spree.t(:my_auctions) %></h3>
  <% if @auctions.any? %>
    <table class="table table-striped order-summary">
      <thead class="active">
        <tr>
          <th><%= Spree.t("title") %></th>
          <th><%= Spree.t("current_price") %></th>
          <th><%= Spree.t("winning?") %></th>
          <th><%= Spree.t("bids") %></th>
          <th><%= Spree.t("current_end_datetime") %></th>
          <th><%= Spree.t("time_remaining") %></th>
          <th><%= Spree.t("order") %></th>
        </tr>
      </thead>
      <tbody>
        <% @auctions.each do |auction| %>
          <% highest_bidder = auction.highest_bidder_id == spree_current_user.id %>
          <tr class="<%= cycle('even', 'odd') %>">
            <td>
              <span class="bold">
                <%= link_to auction.title, auction %>
              </span>
            </td>
            <td>
              <% if highest_bidder %>
                <span class="green">
                  <%= auction.display_current_price %>
                  <% highest_bid = auction.highest_bid %>
                  <% if highest_bid.is_autobid? %>
                    (<%= highest_bid.display_amount %>)
                  <% end %>
                </span>
              <% else %>
                <span class="red">
                  <%= auction.display_current_price %>
                </span>
                <% end %>
              </td>
              <td>
                <% if highest_bidder %>
                  <i class="fa fa-thumbs-up green" aria-hidden="true"></i>
                <% else %>
                  <i class="fa fa-thumbs-down red" aria-hidden="true"></i>
                <% end %>
              </td>
              <td>
                <span class="bold">
                  <%= auction.visible_bids.count %>
                </span>
              </td>
              <td><%= local_time(auction.current_end_datetime) %></td>
              <td>
                <% is_highest_bidder = auction.highest_bidder_id == spree_current_user.id %>
                <% if is_highest_bidder && auction.order_complete? %>
                  <span class="green">
                    <%= Spree.t("complete") %>
                  </span>
                <% elsif is_highest_bidder && auction.won? && !auction.order_complete? %>
                  <%= render partial: 'spree/shared/checkout_in', locals: { auction: auction } %>
                <% elsif auction.in_progress? %>
                  <%= render partial: 'spree/shared/ends_in', locals: { auction: auction } %>
                <% elsif auction.complete? %>
                  <span class="green">
                    <%= Spree.t("complete") %>
                  </span>
                <% end %>
              </td>
              <td>
                <% if auction.complete && highest_bidder %>
                  <%= render partial: 'spree/shared/auction_order_link', locals: { auction: auction } %>
                <% elsif auction.complete %>
                  <span class="red">
                    <i class="fa fa-frown-o" aria-hidden="true"></i>
                  </span>
                <% else %>
                  <span class="red">
                    <%= Spree.t("na") %>
                  </span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-info">
        <p>
          <%= Spree.t(:you_have_not_participated_in_an_auction_yet) %>
          <%= Spree.t(:check_some_out_here) %>:
          <%= link_to Spree.t(:auctions), auctions_path %>
        </p>
      </div>
    <% end %>
    <br />

  </div>

app/views/spree/shared/_ends_in.html.erb
<% if auction.current_end_datetime %>
  <span>
    <%= Spree.t("ends_in") %>
  </span>
  <span class="ends-in red" data-auction-end-datetime=<%= auction.current_end_datetime_as_float%> data-auction-starting-datetime=<%= auction.starting_datetime_as_float%>>
    <% if auction.complete %>
      <span class="green">
        COMPLETE
      </span>
    <% else %>
      <%= distance_of_time_in_words_to_now(auction.current_end_datetime) %>
    <% end %>
  </span>
<% end %>

app/views/spree/shared/_line_item_delete.html.erb
<% if variant.option_values.any? || variant.is_master?%>
  <td class="cart-item-delete" data-hook="">
    <%= link_to image_tag('icons/delete.png'), '#', class: 'delete', id: "delete_#{dom_id(line_item)}" %>
  </td>
<% end %>

app/views/spree/shared/_line_item_link_to.erb
<% if variant.option_values.any? || variant.is_master?%>
  <td class="cart-item-description" data-hook="cart_item_description">
    <h4><%= link_to line_item.name, product_path(variant.product) %></h4>
    <%= variant.options_text %>
    <% if line_item.insufficient_stock? %>
      <span class="out-of-stock">
        <%= t('spree.out_of_stock') %>&nbsp;&nbsp;<br />
      </span>
    <% end %>
    <span class="line-item-description" data-hook="line_item_description">
      <%= line_item_description_text(line_item.description) %>
    </span>
  </td>
<% else %>
  <% auction = variant.auction %>
  <td class="cart-item-description" data-hook="cart_item_description">
    <h4><%= link_to auction.title, auction %></h4>
    <span class="line-item-description" data-hook="line_item_description">
      <%= line_item_description_text(auction.description) %>
    </span>
    &nbsp;<br />
    <span class="line-item-description" data-hook="line_item_checkout_deadline">
      <%= render partial: 'spree/shared/checkout_in', locals: { auction: auction } %>
    </span>
  </td>
<% end %>

app/views/spree/shared/_order_item_description.html.erb
<% if item.variant.option_values.any? || item.variant.is_master?%>
  <td data-hook="order_item_description">
    <h4><%= item.variant.product.name %></h4>
    <%= truncated_product_description(item.variant.product) %>
    <%= "(" + item.variant.options_text + ")" unless item.variant.option_values.empty? %>
  </td>
<% else %>
  <td data-hook="order_item_description">
    <% auction = item.variant.auction %>
    <h4>
      <%= link_to auction.title, auction %>
    </h4>
    <%= truncate_html(auction.description) %>
  </td>
<% end %>

app/views/spree/shared/_starts_in.html.erb
<% if auction.starting_datetime %>
  <span>
    <%= Spree.t("starts_in") %>
  </span>
  <span class="starts-in green" data-auction-end-datetime=<%= auction.current_end_datetime_as_float%> data-auction-starting-datetime=<%= auction.starting_datetime_as_float%>>
    <% if auction.complete %>
      <span class="green">
        COMPLETE
      </span>
    <% else %>
      <%= distance_of_time_in_words_to_now(auction.starting_datetime) %>
    <% end %>
  </span>
<% end %>

app/views/spree/shared/_stock_item_name.html.erb
<% if item.variant.option_values.any? || item.variant.is_master?%>
  <td class="item-name"><%= item.variant.name %></td>
<% else %>
  <td class="item-name"><%= item.variant.auction.title %></td>
<% end %>

app/views/spree/shared/_time_in_words_display.html.erb
<div>
  <% if auction.in_progress? %>
    <%= render partial: 'spree/shared/ends_in', locals: { auction: auction } %>
  <% elsif auction.complete %>
    <span class="green">
      <%= Spree.t("complete") %>
    </span>
  <% else %>
    <%= render partial: 'spree/shared/starts_in', locals: { auction: auction } %>
  <% end %>
</div>

app/views/spree/shared/_variant_row_disable.html.erb
<% if variant.option_values.any? || variant.is_master?%>
  <tr id="<%= spree_dom_id variant %>" data-hook="variants_row" class="<%= "deleted" if variant.deleted? %>">
    <td>
      <% if can? :update_positions, Spree::Variant %>
        <span class="handle"></span>
      <% end %>
    </td>
    <td><%= variant.options_text %></td>
    <td><%= variant.display_price.to_html %></td>
    <td><%= variant.sku %></td>
    <td class="actions">
      <% if can?(:update, variant) %>
        <%= link_to_edit(variant, no_text: true) unless variant.deleted? %>
      <% end %>
      <% if can?(:destroy, variant) %>
        &nbsp;
        <%= link_to_delete(variant, no_text: true) unless variant.deleted? %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/spree/shared/_variant_stock_item_disable.html.erb
<% if variant.option_values.any? || variant.is_master?%>
  <tbody class="variant-stock-items">
    <tr id="<%= spree_dom_id variant %>">
      <td class="no-padding" rowspan="<%= row_count %>">
        <div class='variant-container'>
          <div class='variant-image'>
            <%= render 'spree/admin/shared/image', image: variant.display_image(fallback: false), size: :small %>
          </div>
          <div class='variant-details'>
            <table class='stock-variant-field-table'>
              <tbody>
                <% @variant_display_attributes.each do |display_attribute| %>
                  <tr>
                    <td><%= t(display_attribute[:translation_key], scope: 'spree') %></td>
                    <td class="fullwidth">
                      <%= variant.send(display_attribute[:attr_name]) %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </td>
      <td rowspan="<%= row_count %>">
        <table class='stock-variant-field-table'>
          <% variant.option_values.sort_by(&:option_type_name).each do |option_value| %>
            <tr>
              <td>
                <%= option_value.option_type_presentation %>
              </td>
              <td><%= option_value.presentation %></td>
            </tr>
          <% end %>
        </table>
      </td>
    </tr>
    <% variant.stock_items.each do |item| %>
      <% if @stock_item_stock_locations.include?(item.stock_location) %>
        <tr class="js-edit-stock-item stock-item-edit-row" data-variant-id="<%= variant.id %>" data-stock-item="<%= item.to_json %>" data-stock-location-name="<%= item.stock_location.name %>">
          <%# This is rendered in JS %>
        </tr>
      <% end %>
    <% end %>
    <% if display_add_row %>
      <tr class="js-add-stock-item stock-item-edit-row" data-variant-id="<%= variant.id %>">
        <td class='location-name-cell'>
          <%= select_tag :stock_location_id, options_from_collection_for_select(locations_without_items, :id, :name), { include_blank: true, class: 'custom-select', "data-placeholder" => t('spree.add_to_stock_location'), id: "variant-stock-location-#{variant.id}" } %>
        </td>
        <td class="align-center">
          <%= check_box_tag :backorderable, 'backorderable', false, id: "variant-backorderable-#{variant.id}" %>
        </td>
        <td class="align-center">
          <%= number_field_tag :count_on_hand, "", class: 'fullwidth', id: "variant-count-on-hand-#{variant.id}" %>
        </td>
        <td class="actions">
          <%= link_to_with_icon 'plus', t('spree.actions.create'), '#', no_text: true, data: { action: 'add' }, class: "submit" %>
        </td>
      </tr>
    <% end %>
  </tbody>
<% end %>

app/views/spree/shared/_votes.html.erb
<% votes = auction.cached_votes_up %>
<% if spree_current_user %>
  <% voted_for = spree_current_user.voted_up_on? auction %>
  <div class="votes <%= 'green' if voted_for %>" data-auction-id=<%= auction.id %> data-user-id=<%= spree_current_user.id %> data-voted-for="<%= voted_for ? 'true':'false' %>">
  <% else %>
    <div class="votes" data-auction-id=<%= auction.id %> data-user-id=null>
    <% end %>
    <span>
      <%= votes %>
    </span>
    <i class="fa fa-eye" aria-hidden="true"></i>
  </div>